// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neqymkcnnpkooponhxww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lcXlta2NubnBrb29wb25oeHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzkyNzYsImV4cCI6MjA3NDQ1NTI3Nn0.z7c-WXUQHOme89kOHLTvgpYEzV-Kg_HU9GXheIMIUYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});